#!/bin/bash


#if [ $# -ne 1 ]; then
#    echo "This is a test script for demo only"
#    echo "  -e : for encrypting files in usb_test"
#    echo "  -d : for decrypting files in usb_test"
#    exit 1
#fi

#python3 -m venv /home
#source /home/bin/activate

python3 poc.py
#if [ $1 == "-e" ]; then
#    echo "Encrypting files in usb_test"
#    python3 poc.py e
#elif [ $1 == "-d" ]; then
#    echo "Decrypting files in usb_test"
#    python3 poc.py d
#else
#    echo "Invalid argument"
#    exit 1
#fi
